### ISSUE TITLE
Cannot read properties of undefined (reading 'buildPlaceholders')

### ISSUE THREAD

**Issue by suhmeanhuck** [matfantinel/matfantinel.github.io#18]
Thank you so much for this project Matt! Most of the examples I have come across don't focus on UI, so after I came across yours I was completely blown away!

The source project mostly works for me except the blog posts. If I click on any of them I get the error:

# Error Message:

```
[plugin:vite-plugin-svelte] Error while preprocessing /Users/macuser/Downloads/mat/src/lib/posts/web-workers.md - Cannot read properties of undefined (reading 'buildPlaceholders')
/Users/macuser/Downloads/mat/src/lib/posts/web-workers.md

    at /Users/macuser/Downloads/mat/node_modules/prismjs/components/prism-liquid.js:47:39
    at Object.run (/Users/macuser/Downloads/mat/node_modules/prismjs/prism.js:759:6)
    at Object.highlight (/Users/macuser/Downloads/mat/node_modules/prismjs/prism.js:666:12)
    at code_highlight (/Users/macuser/Downloads/mat/node_modules/mdsvex/dist/main.cjs.js:25782:13)
    at /Users/macuser/Downloads/mat/node_modules/mdsvex/dist/main.cjs.js:25745:25
    at Array.map (<anonymous>)
    at /Users/macuser/Downloads/mat/node_modules/mdsvex/dist/main.cjs.js:25743:11
    at wrapped (/Users/macuser/Downloads/mat/node_modules/mdsvex/dist/main.cjs.js:206:19)
    at next (/Users/macuser/Downloads/mat/node_modules/mdsvex/dist/main.cjs.js:299:28)
    at done (/Users/macuser/Downloads/mat/node_modules/mdsvex/dist/main.cjs.js:236:16
```

The animation will actually loop through all the blog posts and display this error for each.

I don't think it's  related but the only errors that IDE shows is:

- tsconfig.json 
  > Cannot write file '/Users/macuser/Downloads/mat/src/lib/meta.js' because it would overwrite input file.

- posts.js
  > 'Prism' is declared but its value is never read

  > The parsing error: unexpected token import

<img width="646" alt="Screen Shot 2022-02-06 at 2 04 20 AM" src="https://user-images.githubusercontent.com/4127689/152672471-15b992aa-c77c-4875-9b62-534238e9088c.png">

**Comment by matfantinel** [comment]
Hi, thanks for the kind words!

I've faced that one, seems to be an error with the prismjs dependency from MDsveX. It's running with the version I have installed right now  (1.24.1), but seems to break with newer ones. Need to investigate more to see how to properly fix this.

**Comment by suhmeanhuck** [comment]
Thank you Mat. I tried explicitly declaring "prismjs": "1.24.1" in both the devDependencies and dependencies but I'm still getting the same error. I then tried adding "@types/prismjs": "^1.16.8" and uninstalling all of the prism packages but the same error still persists. I wonder if it's from something else.

If I try to go directly (as opposed to clicking through from the home page) to a link using the url (such as http://localhost:3000/2021-year-in-review) then I get the error:

```
`page` in `load` functions has been replaced by `url` and `params`
Error: `page` in `load` functions has been replaced by `url` and `params`
    at Object.get (file:///Users/macuser/Downloads/mat/.svelte-kit/runtime/server/index.js:1768:12)
    at load (__layout.reset.svelte:2:34)
    at load_node (file:///Users/macuser/Downloads/mat/.svelte-kit/runtime/server/index.js:1778:30)
    at respond$1 (file:///Users/macuser/Downloads/mat/.svelte-kit/runtime/server/index.js:2120:21)
    at async render_page (file:///Users/macuser/Downloads/mat/.svelte-kit/runtime/server/index.js:2321:19)
    at async resolve (file:///Users/macuser/Downloads/mat/.svelte-kit/runtime/server/index.js:2564:11)
    at async respond (file:///Users/macuser/Downloads/mat/.svelte-kit/runtime/server/index.js:2497:20)
    at async file:///Users/macuser/Downloads/mat/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```

**Comment by matfantinel** [comment]
@suhmeanhuck oh, that error looks like SvelteKit's API has changed a bit. Seems like it's just variable names so shouldn't be hard to fix. Since it's still a beta this kind of thing is expected.

About the prismjs version, Prism is not a direct dependency from this app, but instead is a dependency from MDsveX. So that's why your approach didn't fix it. For now you can try deleting the node_modules folder and using `npm ci` instead of `npm install`, that way I believe it will use the version on package-lock.json (1.24.1) instead of downloading a newer one.

I'll likely get around to updating the dependencies on my machine soon, so I'll have to fix things up. In case you end up finding a solution sooner than me, please let me know!

**Comment by IHTFY** [comment]
For the Error: ``` `page` in `load` functions has been replaced by `url` and `params` ```

> /src/routes/[slug]/index.svelte

```javascript
export function load({ page }) {
  const { slug } = page.params;
```
becomes
```javascript
export function load({ params }) {
  const { slug } = params;
```

---

> /src/routes/[slug]/__layout.reset.svelte
```javascript
export async function load({ page, fetch }) {
  const slug = page.path.split('/').slice(-1)[0]; // last part of url path
  const url = `/${slug}.json`;
```
becomes
```javascript
export async function load({ fetch, url }) {
  const urlJSON = url.pathname + '.json';
```
and use `urlJSON` instead of `url` on lines 4 & 16.

**Comment by IHTFY** [comment]
@suhmeanhuck I also get the placeholder error, but only when I run `dev` -  the build version works when I `preview`.

**Comment by matfantinel** [comment]
OK, so I just fixed both errors - the SvelteKit one was just a small change (thanks @IHTFY !)

The placeholders one was an issue with the code highlighting inside MDsveX (which uses PrismJS). I had one post with some `liquid` code (inherited from when my website was built with Jekyll), and that highlighting broke in some PrismJS update. I just removed that highlighting since it wasn't important and things worked again.

I also ended up updating MDsveX and PrismJS to fix a vulnerability. All code is updated on `main` branch. Thanks all for reporting and looking into it!
