### ISSUE TITLE
Colocated images / assets for Markdown posts

### ISSUE THREAD

**Issue by willowell** [matfantinel/matfantinel.github.io#36]
Hello!

First off, thank you for open sourcing your blog and keeping a guide on how to make a blog with SvelteKit!

Have you investigated / do you know of any solutions for colocating images and assets with Markdown posts with SvelteKit?

I am investigating SSG frameworks for my personal website. Previously it was a Gatsby site, but I'm exploring building a website with progressive enhancement, preferably with fewer network requests and minimal JS / JSON. As a baseline, I am assuming *no JavaScript functionality at all.*

Still, I really enjoy the UX of writing Markdown posts in Gatsby with colocated images / assets - https://www.gatsbyjs.com/docs/working-with-images-in-markdown/.

Hugo can do something similar with page bundles.

I imagine Gatsby is doing some Webpack magic behind the scenes - I am aware that colocating images / assets is also an issue with Nuxt.js (Vue) and Astro.

**Comment by matfantinel** [comment]
Hi @willowell !

I'm not 100% sure if I understood what you want to do. So feel free to correct me if I understood it wrong.

You can normally reference images on Markdown files in SvelteKit (anything inside the `assets` folder is accessible via a relative/absolute URL). This project just adds an additional layer on top of it, because I have an `<Image>` component that does some of the optimizations described on [this post](https://fantinel.dev/web-images-modern-formats/) (uses Jekyll on code examples, but you can see the current source code if you wanna see Svelte implementation details). It all works without JS and the only additional requests are for the images themselves.

**Comment by willowell** [comment]
Hello @matfantinel!

Thank you for quick response!

I mean something like this:

```
<content root>
└── blog
    ├── my-first-post
    │   ├── a-pdf.pdf
    │   ├── cover-image.png
    │   ├── index.md
    │   └── my-inline-image.png
    └── my-other-post.md
```

where `my-first-post/index.md` references the assets relative to itself like so:

```md
---
title: "Hello World!"
coverImage: ./cover-image.png
---

![A Markdown image](./my-inline-image.png)

[A PDF file](./a-pdf.pdf)
```

This way, all of the website's content is stored in one directory, as opposed to having a duplicated directory structure in the static assets directory, in which case you have to make sure the directory structure is synchronized to prevent broken asset links.

```
<content root>
└── blog
    ├── my-first-post.md
    └── my-other-post.md
```

```
<static assets root>
└── blog
    └── my-first-post
        ├── a-pdf.pdf
        ├── cover-image.png
        └── my-inline-image.png
```

For instance, Tania Rascia stores *most* of the content for her Gatsby website under a private git submodule under `/content/`, ensuring that any clones / forks don't copy her written content: https://github.com/taniarascia/taniarascia.com

Does that make sense?

**Comment by matfantinel** [comment]
@willowell ooh got it! I don't really know of a way of doing that as I've never searched for it, but SvelteKit uses Vite to handle this kind of stuff, and it might be worth looking into [its docs](https://vitejs.dev/guide/build.html#public-base-path) to see if that's possible.

It's likely that after building it will all go into an `assets` folder or similar, but maybe during development you can have them on the post folders

**Comment by willowell** [comment]
@matfantinel Hm, okay! Thank you so much for your help and for taking the time to respond!

I'll keep that in mind and take a look through Vite's docs to see what can be done there.

I will close this issue.

Thanks again!

**Comment by matfantinel** [comment]
Hey @willowell , hopefully you found a way to do what you wanted to do here, but just to let you know, I recently refactored this entire project and now a post's images are sitting alongside the Markdown files themselves like you wanted. This was possible because instead of just pointing to a URL like before (which only worked for the /static folder), I'm actually importing the images via JS. This allows preprocessing them which was my main goal with this.

**Comment by willowell** [comment]
Hello @matfantinel! Sorry for my late reply - thank you so much for following up!

That's awesome - I'm glad to hear that!

I've settled on Astro (https://astro.build/) for my personal website - I've found it meets my criteria the best at the moment.
