### ISSUE TITLE
Extract a generic template from this website

### ISSUE THREAD

**Issue by matfantinel** [matfantinel/matfantinel.github.io#46]
There's been some interest in having this site available as a generic template for people to more easily fork and build their own. This is already being done in a way with the `data/*` folders, but there are still some hardcoded strings, and ideally there'd be a well-defined set of steps with things to change when forking the template.

One thing to keep in mind is how can I keep this template easy to get started with but still be able to toy around with stuff since it's also my personal website. Would making my website a fork of it add too much complexity? For example, if I decide to add #15 on my fork first, how easy would it be to backport just that into this template?

**Comment by xKesvaL** [comment]
Wouldn't that depend on how you are deploying your website ?
Personally, I'm using Vercel and I know if I wanted to, I could only deploy a specific branch of my repo. Maybe then you create your personnal website branch and the only things that differ between the main (template) branch and yours is the data folder and the blog folder (example blog posts for the template ig?).

You would keep the ability to make changes on your website easily, and also would be able to transfer these changes to the template, while keeping your data and posts apart from it.

Let me know what you think, I'm interested in that since your website is the one that helped me learn Svelte and I couldn't thank you more for that haha.

**Comment by matfantinel** [comment]
@xKesvaL I actually chose to completely separate my website from the template. I think the template is in a good enough state to be a starting point and having them separate is a good thing, as I still want my website to be my playground.

For the record, the template is done and lives here: https://github.com/matfantinel/sveltekit-static-blog-template
However there's still an issue with the image optimization I'm trying to fix. I took the chance to simplify some things and will backport these changes into this repo when I get the time.

P.S.: This website is actually hosted on Vercel now, not GitHub Pages. Where did you see it being hosted in GH Pages? I may have forgotten to update something

**Comment by xKesvaL** [comment]
@matfantinel Oh right! Didn't see that template, that's pretty nice.

I'm gonna look into your image optimization because, while i've been using your [Image transmutation](https://github.com/matfantinel/image-transmutation) tool, I would really like to have out of the box image optimization.

I didn't really see it, I mean it's still saying on the repo homepage that it's hosted on gh-pages, but at first I thought it was because of the name of the repo.

**Comment by matfantinel** [comment]
@xKesvaL This website has automated image optimization using [vite-imagetools](https://github.com/JonasKruckenberg/imagetools) which works quite well. However, it requires actually importing images (in the script part of the code) for them to be optimized. That's fine on components, but a bit cumbersome on blog posts (especially the cover image).

However I'm trying a different approach with the template. If I'm able to get it working well, I'll update it here as well. Feel free to [help me brainstorm if you want](https://github.com/matfantinel/sveltekit-static-blog-template/issues/1), as that codebase is smaller and simpler to wrap your head around

**Comment by xKesvaL** [comment]
@matfantinel Yeah I knew about vite-imagetools but as you said, it's not so fun sometimes, that's why I don't use it.

I'm gonna have a look into what you sent!
